services:
  redis:
    image: redis
    ports:
      - '6379:6379'
  redis-api:
    ports:
      - '8079:80'
    image: hiett/serverless-redis-http:latest
    environment:
      SRH_MODE: env
      SRH_TOKEN: ${SRH_TOKEN}
      SRH_CONNECTION_STRING: 'redis://redis:6379'
